<a href="https://colab.research.google.com/github/Gurmandeep-Kaur/UML501_102303764_GURMANDEEP/blob/main/Assignment1_102303764.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
import numpy as np

In [76]:
# 1(a)
arr = np.array([1,2,3,6,4,5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

Reversed array: [5 4 6 3 2 1]


In [77]:
# 1(b)
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])

# Method 1
flat1 = array1.flatten()
print("Flattened (flatten):", flat1)

# Method 2
flat2 = array1.ravel()
print("Flattened (ravel):", flat2)

Flattened (flatten): [1 2 3 2 4 5 1 2 3]
Flattened (ravel): [1 2 3 2 4 5 1 2 3]


In [78]:
# 1(c)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

# Element-wise comparison
print("Elements equal? \n", arr1==arr2, "\n")
# Entire array comparison
print("Arrays equal?", np.array_equal(arr1,arr2))

Elements equal? 
 [[ True  True]
 [ True  True]] 

Arrays equal? True


In [79]:
# 1(d)(i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
val, count = np.unique(x, return_counts=True)
most_freq = val[np.argmax(count)]
indices = np.where(x == most_freq)
print("Most frequent in x:", most_freq)
print("Indices:", indices, "\n")

# 1(d)(ii)
y = np.array([1,1,1,2,3,4,2,4,3,3])
val, count = np.unique(y, return_counts=True)
most_freq = val[np.argmax(count)]
indices = np.where(y == most_freq)
print("Most frequent in y:", most_freq)
print("Indices:", indices)

Most frequent in x: 1
Indices: (array([0, 5, 7, 8, 9]),) 

Most frequent in y: 1
Indices: (array([0, 1, 2]),)


In [80]:
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')

print("Total sum:", gfg.sum(), "\n") # 1(e)(i)
print("Row-wise sum:\n", gfg.sum(axis=1), "\n") # 1(e)(ii)
print("Column-wise sum:",gfg.sum(axis=0)) # 1(e)(iii)

Total sum: 45 

Row-wise sum:
 [[14]
 [16]
 [15]] 

Column-wise sum: [[20  9 16]]


In [81]:
# 1(f)(i)
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Sum of diagonal elements:", np.trace(n_array), "\n")

# 1(f)(ii), 1(f)(iii)
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors, "\n")

# 1(f)(iv)
inverse = np.linalg.inv(n_array)
print("Inverse:", inverse, "\n")

# 1(f)(v)
determinant = np.linalg.det(n_array)
print("Determinant:", determinant)

Sum of diagonal elements: 176 

Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]] 

Inverse: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]] 

Determinant: 137180.0000000001


In [82]:
# 1(g)(i)
p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])
print("Matrix product:\n", np.dot(p,q), "\n")
print("Covarience:\n", np.cov(p.T,q.T), "\n")

# 1(g)(ii)
p = np.array([[1,2],[2,3],[4,5]])
q = np.array([[4,5,1],[6,7,2]])
print("Matrix product:\n", np.dot(p,q), "\n")
print("Covarience:\n", np.cov(p.T,q))

Matrix product:
 [[16 19]
 [26 31]] 

Covarience:
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]] 

Matrix product:
 [[16 19  5]
 [26 31  8]
 [46 55 14]] 

Covarience:
 [[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [83]:
# 1(h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product (dot product of rows)
print("Inner product:\n", np.inner(x, y), "\n")

# Outer product (element-wise outer)
print("Outer product:\n", np.outer(x.flatten(), y.flatten()), "\n")

# Cartesian product using meshgrid
from itertools import product
cartesian = np.array(list(product(x.flatten(), y.flatten())))
print("Cartesian product:\n", cartesian)

Inner product:
 [[17 52]
 [13 62]] 

Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]] 

Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [84]:
array = np.array([[1,-2,3],[-4,5,-6]])

# 2(a)(i)
print("Absolute:\n", np.abs(array),"\n")

# 2(a)(ii)
flat = array.flatten()
print("Percentiles (flat):", np.percentile(flat, [25,50,75]))
print("Percentiles (column):\n", np.percentile(array, [25,50,75], axis=0))
print("Percentiles (row):\n", np.percentile(array, [25,50,75], axis=1),"\n")

# 2(a)(iii)
print("Mean (flat):", flat.mean())
print("Median (flat):", np.median(flat))
print("Std (flat):", np.std(flat),"\n")

print("Mean (column):", array.mean(axis=0))
print("Median (column):", np.median(array, axis=0))
print("Std (column):", np.std(array, axis=0),"\n")

print("Mean (row):", array.mean(axis=1))
print("Median (row):", np.median(array, axis=1))
print("Median (row):", np.std(array, axis=1),"\n")

Absolute:
 [[1 2 3]
 [4 5 6]] 

Percentiles (flat): [-3.5 -0.5  2.5]
Percentiles (column):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (row):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]] 

Mean (flat): -0.5
Median (flat): -0.5
Std (flat): 3.8622100754188224 

Mean (column): [-1.5  1.5 -1.5]
Median (column): [-1.5  1.5 -1.5]
Std (column): [2.5 3.5 4.5] 

Mean (row): [ 0.66666667 -1.66666667]
Median (row): [ 1. -4.]
Median (row): [2.05480467 4.78423336] 



In [85]:
# 2(b)
a = np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Truncate:", np.trunc(a))
print("Round:", np.round(a))

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Truncate: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


In [86]:
array = np.array([10,52,62,16,16,54,453])

# 3(a)(i)
sorted_arr = np.sort(array)
print("Sorted array:", sorted_arr)

# 3(a)(ii)
print("Sorted indices:", np.argsort(array))

# 3(a)(iii)
print("4 smallest elements:", sorted_arr[:4])

# 3(a)(iv)
print("5 largest elements:", sorted_arr[-5:])

Sorted array: [ 10  16  16  52  54  62 453]
Sorted indices: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [87]:
array = np.array([1.0,1.2,2.2,2.0,3.0,2.0])

# 3(b)(i)
int_vals = array[np.floor(array)==array]
print("Integer values:", int_vals)

# 3(b)(ii)
float_vals = array[np.floor(array)!=array]
print("Float values:", float_vals)

Integer values: [1. 2. 3. 2.]
Float values: [1.2 2.2]


In [88]:
import cv2
import matplotlib.pyplot as plt

In [89]:
def img_to_array(path):
    image = cv2.imread(path)

    if image is not None:
        if len(image.shape) == 2:
            # Grayscale image
            print("Grayscale image detected\n")
            np.savetxt("/content/grayscale.txt", image, fmt='%d')

            # Loading the saved file
            gray_image = np.loadtxt("/content/grayscale.txt", dtype=np.uint8)
            plt.imshow(gray_image, cmap='gray')
            plt.title("Grayscale Image")
            plt.axis('off')
            plt.show()

        elif len(image.shape) == 3:
            # Color image
            print("Color image detected\n")
            image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            np.save("/content/color.npy", image_rgb)

            # Loading the saved file
            color_image = np.load("/content/color.npy")
            plt.imshow(color_image)
            plt.title("Color Image")
            plt.axis('off')
            plt.show()

        else:
            print("Unknown image format")
    else:
        print("Failed to read image.")

#img_to_array("/My folder/Colored_image.webp")